### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by southpolesteve**
Fix links that previously pointed to preview

### CODE REVIEW

**Comment by christopheranderson** [comment]
We should do this into dev first, or does this need to be hotfixed into master?

**Comment by southpolesteve** [comment]
Master. The links 404 on master right now

**Comment by christopheranderson** [comment]
It'll 404 on npm as well. We need to do a full patch release to update npm, right?

**Comment by southpolesteve** [comment]
Yes

**Comment by christopheranderson** [comment]
Maybe just update this PR with the package update info, then? We'll need to cherry pick this back onto dev, as well.

**Comment by southpolesteve** [comment]
@christopheranderson Bumped the version in here. As soon as this passes it can be merged and published to npm.

**Comment by christopheranderson** [comment]
Adding that version checking test looks like it was worth it :)

**Comment by southpolesteve** [comment]
This will not be the last time that test bites me

**Pull request merged**
