### PR TITLE
Output transpiled test files to dist-test directory

### PR DESCRIPTION
**Pull request by jeremymeng**
to keep test directory clean

### CODE REVIEW

**Comment by jeremymeng** [comment]
I found that output files along side *.ts files make navigating in the VS Code explorer a little harder. thoughts? @southpolesteve

**Comment by southpolesteve** [comment]
I would actually like to go the other direction and not emit at all. Both @christopheranderson and I have hit bugs with typescript projects and vscode and it has been a bit frustrating. I think my ideal setup is:

- `npm run compile` should just type check, no emit
- `npm run test` should use ts-node/transpileOnly to run .ts tests directly
-  `npm run build` should emit just src since it has some extra compiler options like noUnusedLocals

**Comment by jeremymeng** [comment]
Does ts-node work with browser tests? (I noticed that npm run test-browser seems broken in 3 branch.)

Sent from my Windows 10 device

________________________________

**Comment by southpolesteve** [comment]
Browser tests aren't working right now. Its something we need to fix.

**Comment by jeremymeng** [comment]
Abandoning

**Pull request closed without merging**
