### PR TITLE
Remove sourcemap from the bundle in webpack -p mode. Helps #61

### PR DESCRIPTION
**Pull request by alippai**
This way it's only 323kB (86kB gzipped)

### CODE REVIEW

**Comment by alippai** [comment]
After running `npm run build-prod` instead of `npm run build` it's 279kB (74kB gzipped)

**Comment by alippai** [comment]
@christopheranderson This is more like a bugfix for the current RC (as a temporary solution) while #104 (nice!) lands.

I didn't notice the PR (#104) before, just the issue (#61) and I thought this is something I can improve. Feel free to close this PR :)

| What | Time |
|--------------------------|--------|
| Loading the lib/index.js | >150ms |
| Loading the old lib/dist/azurecosmos.js | >100ms |
| Loading the new lib/dist/azurecosmos.js produced with the new build-prod | ~40ms |

**Comment by southpolesteve** [comment]
@alippai Thank you for this PR! Wanted to let you know I'll be looking at it soon. I need to have a larger discussion with the team and how it fits in with #104. Hopefully this next week.

**Comment by southpolesteve** [comment]
@alippai Thanks for this! Going to merge it in now. We may make some tweaks once #104 lands, but at least right now this is helpful as we try to ensure the SDK is slim for browser users.

**Pull request merged**
